### ISSUE TITLE
nocrypto 0.5.4 failed

### ISSUE THREAD

**Issue by tsh-box** [me-box/databox#218] opened 2017-12-18 05:14 UTC
Hello,

It failed in nocrypto0.5.4.
Please could you tell me ,how can I solve it?

![tocon11](https://user-images.githubusercontent.com/29420329/34090865-5e44209a-e3fd-11e7-9de4-dfebff4cd895.png)

**Comment by sevenEng** [comment] 2017-12-18 11:30
You may want to check the version of `topkg`. As added here: https://github.com/ocaml/opam-repository/blob/master/packages/nocrypto/nocrypto.0.5.4/opam#L37
nocrypto.0.5.4 works with topkg.0.9.1, and the line
```
pkg.ml: [ERROR] key --jobs: Unknown key
```
indicates you have a stale version of `topkg`

**Comment by sevenEng** [comment] 2017-12-18 11:32
I think it was caused by `core-network`?
This has been fixed in the latest 0.3.1, you can try with the latest version, hope that'll help.

**Comment by tsh-box** [comment] 2017-12-19 01:18
Thanks you, @sevenEng 
May I ask one question,I have forked the all of repositories from me-box because of the version management of Databox.
I forked the Version 0.3.0 
Question, when me-box have version upgraded,my forked repositories(in ver 0.3.0) also influence or  may be occur error?

**Comment by haddadi** [comment] 2017-12-19 07:17
Please see https://help.github.com/articles/fork-a-repo/

also familiarise yourself with the licensing requirements  http://www.linfo.org/mitlicense.html

Unfortunately we do not have the bandwidth to provide debugging for forked projects.

**Closed as completed by haddadi** 2017-12-19 07:17 UTC

**Comment by tsh-box** [comment] 2017-12-19 08:12
@sevenEng  I have same error even used the latest version 0.3.1

**Comment by tsh-box** [comment] 2017-12-19 08:13
@haddadi  Thank you for your guidance

**Comment by sevenEng** [comment] 2017-12-19 10:43
@tsh-box I have the same expectation with you that an upgrade should not break a previous version. But the problem is not from Databox per se, but from a upstream package *(nocrypto.0.5.4)*,  it did an online [update](https://github.com/ocaml/opam-repository/commit/5436eaf17c593943f4d9c8b9ea101f364297e99b#diff-10d432b148f1719ee44de8c52934f545) of the build script for that specific version without rolling out a new version, which may not be the best practice, also the first attempt of doing this actually missed some version constraints *(topkg >= 0.9.1)*, and caused this problem. But this was picked up by our automatic travis build fairly quickly, and  issues were filed, PR was submitted and merged. On our side, we also [patched up core-network](https://github.com/me-box/core-network/commit/d1cf119f70698848c651814c3d30a56c41d0dbe3) to deal with this in 0.3.1.

**Comment by tsh-box** [comment] 2017-12-21 05:29
I solved it :)
