### ISSUE TITLE
Docker Network API issue - when creating network first time

### ISSUE THREAD

**Issue by pooyadav** [me-box/databox#29] opened 2017-04-06 10:46 UTC
sudo ./startDatabox.sh
databox-cm
databox-cm
Using default tag: latest
latest: Pulling from databoxsystems/databox-cm
709515475419: Already exists 
3a1efd78d579: Already exists 
c348f8c5514b: Already exists 
885457137c4d: Pull complete 
14c428473cb1: Pull complete 
959128bbdb5b: Pull complete 
26279b8e5c43: Pull complete 
Digest: sha256:b24d6723695a9bcddb19354bc3c31b440cf368e856ee7b6dc6bff47db6903456
Status: Downloaded newer image for databoxsystems/databox-cm:latest
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.8.0
npm info lifecycle databox-container-manager@0.1.0~prestart: databox-container-manager@0.1.0
npm info lifecycle databox-container-manager@0.1.0~start: databox-container-manager@0.1.0

> databox-container-manager@0.1.0 start /
> node src/main.js

ERROR creating databox-cloud-net { Error: (HTTP code 500) server error - unable to remove jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -D FORWARD -j DOCKER-ISOLATION: iptables: No chain/target/match by that name.
 (exit status 1)) 
    at /node_modules/docker-modem/lib/modem.js:239:17
    at getCause (/node_modules/docker-modem/lib/modem.js:269:7)
    at Modem.buildPayload (/node_modules/docker-modem/lib/modem.js:238:5)
    at IncomingMessage.<anonymous> (/node_modules/docker-modem/lib/modem.js:214:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  reason: 'server error',
  statusCode: 500,
  json: { message: 'unable to remove jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -D FORWARD -j DOCKER-ISOLATION: iptables: No chain/target/match by that name.\n (exit status 1))' } }
ERROR creating databox-driver-net { Error: (HTTP code 500) server error - unable to remove jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -D FORWARD -j DOCKER-ISOLATION: iptables: No chain/target/match by that name.
 (exit status 1)) 
    at /node_modules/docker-modem/lib/modem.js:239:17
    at getCause (/node_modules/docker-modem/lib/modem.js:269:7)
    at Modem.buildPayload (/node_modules/docker-modem/lib/modem.js:238:5)
    at IncomingMessage.<anonymous> (/node_modules/docker-modem/lib/modem.js:214:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  reason: 'server error',
  statusCode: 500,
  json: { message: 'unable to remove jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -D FORWARD -j DOCKER-ISOLATION: iptables: No chain/target/match by that name.\n (exit status 1))' } }
npm info lifecycle databox-container-manager@0.1.0~

**Comment by yousefamar** [comment] 2017-04-06 10:49
Not sure if this will help, but it may be worth a shot to remove all existing networks. Could be a remnant of config from one of the older versions:

    docker network rm $(docker network ls -q)

**Comment by Toshbrown** [comment] 2017-04-06 10:57
confirmed only happens sometimes on the first install with no networks created previously.

**Comment by yousefamar** [comment] 2017-04-06 10:59
Perhaps a Docker bug, since [this](https://github.com/docker/docker/issues/25393) was last referenced in an open issue two days ago.

> This looks like a duplicate of #25393, and #16816. The first one should be resolved in docker 17.04, which will be released this week

**Comment by Toshbrown** [comment] 2017-04-06 11:02
cool, good spot. Looks "concurrency issue" so we might be able to work around it by creating the networks sequentially.

**Comment by Toshbrown** [comment] 2017-04-07 13:28
This has been fixed in the development branch. Will be in the next release.

**Closed as completed by Toshbrown** 2017-04-07 13:28 UTC
Labels: bug
